services:
  # Strapi (Backend)
  - type: web
    name: strapi-cms
    env: node
    plan: free
    repo: https://github.com/cablocoataide-sys/siteallan
    buildCommand: cd strapi-cms && npm install && npm run build
    startCommand: cd strapi-cms && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: TRANSFER_TOKEN_SALT
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_URL
        fromDatabase:
          name: strapi-db
          property: connectionString

  # Frontend (Static Site)
  - type: static_site
    name: site-portfolio
    repo: https://github.com/cablocoataide-sys/siteallan
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_STRAPI_URL
        fromService:
          type: web
          name: strapi-cms
          envVarKey: RENDER_EXTERNAL_URL

databases:
  - name: strapi-db
    plan: free
    databaseName: strapi
    user: strapi
